package ktastic7.unsc.corecontinued.world;

import com.fs.starfarer.api.Global;
import com.fs.starfarer.api.campaign.FactionAPI;
import com.fs.starfarer.api.campaign.PlanetAPI;
import com.fs.starfarer.api.campaign.SectorEntityToken;
import com.fs.starfarer.api.campaign.StarSystemAPI;
import com.fs.starfarer.api.campaign.econ.MarketAPI;
import com.fs.starfarer.api.impl.campaign.ids.Factions;
import indevo.exploration.stations.DerelictStationPlacer;
import indevo.industries.artillery.entities.WatchtowerEntityPlugin;
import indevo.industries.artillery.utils.ArtilleryStationPlacer;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;

/**
 * Optional Industrial Evolution integration kept in its own class so that
 * UNSCStar can gate class loading before any IndEvo-specific symbol is used.
 */
public final class UNSCIndEvoIntegration {

    private static final String RAILGUN_INDUSTRY_ID = "IndEvo_Artillery_railgun";
    private static final String ARSENAL_STATION_ID = "IndEvo_arsenalStation";

    private UNSCIndEvoIntegration() {
    }

    public static void addReachRailgun(PlanetAPI reach, MarketAPI reachMarket) {
        ArtilleryStationPlacer.addArtilleryToPlanet(reach, true);
        reachMarket.addIndustry(RAILGUN_INDUSTRY_ID);
    }

    private static String stableJumpKey(SectorEntityToken jump) {
        if (jump == null) return "";
        String id = jump.getId();
        if (id == null) id = "";
        return id.toLowerCase(Locale.ROOT);
    }

    /**
     * Select the authored system's autogenerated outer/fringe jump point without
     * relying on whatever order StarSystemAPI.getJumpPoints() happens to return.
     * A jump whose stable entity id identifies it as fringe/outer is preferred;
     * otherwise the remaining non-Tribute jump points are sorted by stable id as a
     * deterministic fallback.
     */
    private static SectorEntityToken findOuterJumpPoint(StarSystemAPI system, SectorEntityToken tributeJump) {
        if (system == null) return null;

        List<SectorEntityToken> candidates = new ArrayList<SectorEntityToken>();
        String tributeId = tributeJump == null ? null : tributeJump.getId();

        for (SectorEntityToken jump : system.getJumpPoints()) {
            if (jump == null) continue;
            if (jump == tributeJump) continue;
            if (tributeId != null && tributeId.equals(jump.getId())) continue;

            String key = stableJumpKey(jump);
            if (key.contains("fringe") || key.contains("outer")) {
                return jump;
            }
            candidates.add(jump);
        }

        if (candidates.isEmpty()) return null;
        Collections.sort(candidates, new Comparator<SectorEntityToken>() {
            @Override
            public int compare(SectorEntityToken a, SectorEntityToken b) {
                return stableJumpKey(a).compareTo(stableJumpKey(b));
            }
        });
        return candidates.get(0);
    }

    private static SectorEntityToken spawnWatchtower(SectorEntityToken focus, FactionAPI faction) {
        if (focus == null || faction == null) return null;
        return WatchtowerEntityPlugin.spawn(focus, faction);
    }

    /**
     * Late worldgen stage. At this point the authored gate and autogenerated
     * fringe jump point exist, allowing us to place exactly four watchtowers
     * without invoking IndEvo's system-wide auto-placement pass (which would
     * also populate the asteroid belts).
     */
    public static void addEpsilonEridaniSupport(StarSystemAPI system,
            PlanetAPI betaGabriel,
            SectorEntityToken tributeJump,
            SectorEntityToken inactiveGate,
            float innerBeltDistance) {

        if (system == null || Global.getSector() == null) return;
        FactionAPI unscFaction = Global.getSector().getFaction("unsc_cc");
        if (unscFaction == null) return;

        // 1) Tribute jump point.
        spawnWatchtower(tributeJump, unscFaction);

        // 2) Deterministically selected autogenerated outer/fringe jump point.
        SectorEntityToken outerJump = findOuterJumpPoint(system, tributeJump);
        spawnWatchtower(outerJump, unscFaction);

        // 3) Inactive travel gate.
        spawnWatchtower(inactiveGate, unscFaction);

        // 4) Beta Gabriel, forced to the requested 350-unit orbit instead of
        // IndEvo's default focus-radius + 250 placement.
        SectorEntityToken betaTower = spawnWatchtower(betaGabriel, unscFaction);
        if (betaTower != null && betaGabriel != null) {
            betaTower.setCircularOrbitWithSpin(betaGabriel, 300f, 350f, 35f, 5f, 5f);
        }

        // Native IndEvo salvage entity in the inner asteroid belt. Keeping the
        // default "Arsenal Station" name preserves normal player expectations.
        SectorEntityToken arsenal = DerelictStationPlacer.addSalvageEntity(
                system, ARSENAL_STATION_ID, Factions.NEUTRAL);
        if (arsenal != null) {
            arsenal.setId("unsc_cc_indevo_arsenal_station");
            arsenal.setCircularOrbit(system.getStar(), 250f, innerBeltDistance, 1075f);
        }
    }
}
